services:
  database:
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuperSecretPassw0rd!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - smart_campus_mssql_data:/var/opt/mssql
    networks:
      - PAF_project_network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'SuperSecretPassw0rd!' -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  db-init:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: smart_campus_db_init
    restart: "no"
    user: root
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./init.sql:/init.sql
    networks:
      - PAF_project_network
    # This command runs the script and exits immediately after
    entrypoint: /bin/bash -c "/opt/mssql-tools18/bin/sqlcmd -S database -U sa -P 'SuperSecretPassw0rd!' -C -i /init.sql"
    

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - smart_campus_maven_repo:/root/.m2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://database:1433;databaseName=smart_campus_v1;encrypt=true;trustServerCertificate=true
      # - SPRING_DATASOURCE_URL=jdbc:sqlserver://database:1433;databaseName=master;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=SuperSecretPassw0rd!
    networks:
      - PAF_project_network
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 3600s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - INTERNAL_API_URL=http://backend:8080
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      # - WATCHPACK_POLLING=1000
      # - CHOKIDAR_USEPOLLING=true
    networks:
      - PAF_project_network
    depends_on:
      backend:
        condition: service_healthy # Only starts frontend after backend passes healthcheck

networks:
  PAF_project_network:
    driver: bridge

volumes:
  smart_campus_mssql_data:
  smart_campus_maven_repo: