package com.smartcampus.backend.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * TicketAttachment Entity - Stores the Minio-generated file name for an image
 * that was uploaded as evidence for an incident ticket.
 *
 * A ticket can have AT MOST 3 attachments (enforced in TicketService).
 *
 * Maps to the "TicketAttachments" table defined in the database schema.
 */
@Entity
@Table(name = "TicketAttachments")
public class TicketAttachment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Id")
    private Integer id;

    /** The ticket this attachment belongs to. */
    @Column(name = "TicketId", nullable = false, length = 50)
    private String ticketId;

    /**
     * Unique file name generated by MinioService.
     * Format : {epochSeconds}_{userId}_{originalName}.{ext}
     * Example: 1711025800_usr1001_tint1.jpg
     */
    @Column(name = "GeneratedFileName", nullable = false, length = 255)
    private String generatedFileName;

    @Column(name = "UploadedAt", nullable = false)
    private LocalDateTime uploadedAt;

    // ── Constructors ──────────────────────────────────────────────────────────

    public TicketAttachment() {}

    public TicketAttachment(String ticketId, String generatedFileName) {
        this.ticketId          = ticketId;
        this.generatedFileName = generatedFileName;
        this.uploadedAt        = LocalDateTime.now();
    }

    // ── Getters & Setters ─────────────────────────────────────────────────────

    public Integer getId() { return id; }
    public void setId(Integer id) { this.id = id; }

    public String getTicketId() { return ticketId; }
    public void setTicketId(String ticketId) { this.ticketId = ticketId; }

    public String getGeneratedFileName() { return generatedFileName; }
    public void setGeneratedFileName(String generatedFileName) { this.generatedFileName = generatedFileName; }

    public LocalDateTime getUploadedAt() { return uploadedAt; }
    public void setUploadedAt(LocalDateTime uploadedAt) { this.uploadedAt = uploadedAt; }
}